Update generate.py to generate opengraph tags
pyladies/global-conference pull request #40
Opened 2023-09-07 19:50 UTC by Mariatta

2023-09-08 11:13 UTC, trallard requested changes

2023-09-08 11:13 UTC, trallard commented on web/README.md
> +variable where we added ``og_title``, etc. to the ``about`` and ``index`` pages.
```suggestion
To add this info, refer to the `og_meta` tags defined for the current templates (about, index) in `generate.py`.
```
 
I found the previous wording a bit confusing, so this is more of an optional suggestion than a hard-needed change.

2023-09-08 11:13 UTC, trallard commented on web/generate_site/generate.py
> +        print(f"writing {f=}")
Thank you 🙏🏽 - knowing when things are happening is useful

2023-09-08 11:13 UTC, trallard commented on web/generate_site/generate.py
> +        "og_image_url": "https://conference.pyladies.com/img/icon.png",
```suggestion
        "og_image_url": "https://conference.pyladies.com/img/icon.png",
        "og_image_alt": "PyLadiesCong logo',
```
Let's add alt text to our images to make these accessible to screen readers and other assistive tech

2023-09-08 11:13 UTC, trallard commented on web/generate_site/generate.py
> +        "og_image_url": "https://conference.pyladies.com/img/icon.png",
```suggestion
        "og_image_url": "https://conference.pyladies.com/img/icon.png",
        "og_image_alt": "PyLadiesCong logo',
```

2023-09-08 11:13 UTC, trallard commented on web/generate_site/templates/head.html
> +    <meta property="og:image" content="{{ og_image_url }}">
```suggestion
    <meta property="og:image" content="{{ og_image_url }}">
    <meta property="og:image:alt" content="{{ og_image_alt }}">
```

Ref: https://ogp.me/#structured

2023-09-08 11:15 UTC, trallard commented
Thanks, @Mariatta - I added some comments and suggestions considering that all our images have non-descriptive names such as "icon" it is important to add some alt-text to make the content accessible.

2023-09-08 17:25 UTC, Mariatta commented
Thanks! Please re-review. I committed the changes and fixed some typos.

2023-09-09 12:21 UTC, trallard approved these changes
Looks great, thanks ✨

2023-09-09 12:21 UTC, merged